### ISSUE TITLE
安装主题后没有内容显示

### ISSUE THREAD

**Issue by weank1984** [elmorec/hexo-theme-inside#13]
hi,你好:
    感谢你的工作,inside是一个十分漂亮的主题.
    在我clone到theme文件夹并按照提示修改配置后,页面只有一张背景图片.请问我应该怎么修复?

**Comment by elmorec** [comment]
只要是按照官方的修改主题的步骤，不应该有问题啊，试试别的主题会不会？

**Comment by weank1984** [comment]
我又安装了next主题,显示是正常的...

**Comment by elmorec** [comment]
你是不是用了 `hexo serve`？是的话看下这里 [#2](2#issuecomment-392800470)

**Comment by weank1984** [comment]
真的是这样/😂,多谢了/抱拳

**Comment by elmorec** [comment]
@weank1984 现在可以正常 `hexo serve` 了 🙈

**Comment by weank1984** [comment]
@elmorec 好的,多谢你的工作.
