### ISSUE TITLE
seo优化

### ISSUE THREAD

**Issue by imagemlt** [elmorec/hexo-theme-inside#14]
感觉好像不是很好做seo....想了解一下百度收录的情况怎么样

**Comment by elmorec** [comment]
spa的seo的确不好搞，不过有加sitemap和meta标签，如果喜欢这个ui，有空我另起一个纯html，纯页面跳转的主题，seo就没问题了😅。

**Comment by imagemlt** [comment]
谢谢啦作者辛苦了
