### ISSUE TITLE
子目录

### ISSUE THREAD

**Issue by ListenPlum** [elmorec/hexo-theme-inside#16]
如果使用子目录发布
```yaml
url: http://xxxxx/my_blog
root: /my_blog/
```

>### 会找不到  /api 下的资源，页面死循环

![dnvu1h9 6 aw c9afp 6 i](https://user-images.githubusercontent.com/34758510/41159367-e65ce4ec-6b5e-11e8-85ac-f834cb3507d5.png)

**Comment by elmorec** [comment]
是哦，没考虑到！多谢支持，我尽快修复 😨。

**Comment by elmorec** [comment]
@ListenPlum 已修复

**Comment by ListenPlum** [comment]
Thanks！希望您的主题能够持续更新，很喜欢这套
