### ISSUE TITLE
手机浏览器上发生错位

### ISSUE THREAD

**Issue by xujiaji** [elmorec/hexo-theme-inside#21]
手机浏览器上看一篇比较长的文章发生错位！
https://blog.xujiaji.com/post/learn-dagger
![screenshot_2018-06-28-11-48-06-227_com android ch](https://user-images.githubusercontent.com/16447251/42012172-78184f10-7ac9-11e8-9102-b22d163639eb.png)

**Comment by elmorec** [comment]
![image](https://user-images.githubusercontent.com/9206414/42012498-0f12767e-7acb-11e8-93bc-dbbbb6e958d7.png)
对于 \`code\`，目前的显示规则并没有设置强制换行，`DaggerCoffeeShop.builder().dripCoffeeModule(new DripCoffeeModule()).build();` 太长了。
...
刚看了下 github 的样式，有强制换行，我改一下。

**Comment by xujiaji** [comment]
原来如此，我还以为文章太长导致呢。。。
