### ISSUE TITLE
The style of default markdown code block is bad.

### ISSUE THREAD

**Issue by yorushika** [elmorec/hexo-theme-inside#23]
I'm back again! XD

You can check this article: https://sh.yorushika.xyz/post/code-of-markdown

The first method of code block(markdown default) looks so terrible!

**Comment by elmorec** [comment]
Fixed, I don't use this syntax very much.
Btw, thanks for the support.

**Comment by yorushika** [comment]
Can I add your blog as friend-link? XD

**Comment by elmorec** [comment]
Sure, if u don't mind those poor posts. (Escape)

**Comment by yorushika** [comment]
Though not so many but seems kinda interesting, lol
