### ISSUE TITLE
关于menu专栏文章日期和评论系统

### ISSUE THREAD

**Issue by yorushika** [elmorec/hexo-theme-inside#24]
懒得打英文了Orz

目前发现添加进menu里的页面(about, link等等)都没有办法开启评论系统,无论是否添加comments条目

感觉about里加一个评论还好昂,可以拿来当和博主的直接留言.

然后就是日期问题,如果md里没有date表头,那显示的日期固定为文件修改日期.但about啊link啊这种地方应该不需要日期才对Orz

**Comment by elmorec** [comment]
Morning~
page 目前没加评论，可以加一个。
page 显示日期好像的确意义不大。

待会改一下好了 ^_^

**Comment by yorushika** [comment]
你最胖啦！

**Comment by elmorec** [comment]
现在 page 和 post 一样，默认启用 comments，官方就是如此，若需要禁用 comments，可在 front matter 里设置 `comments: false`。
