### ISSUE TITLE
提个小需求

### ISSUE THREAD

**Issue by xujiaji** [elmorec/hexo-theme-inside#25]
忍了这个好一阵子了:satisfied:
![image](https://user-images.githubusercontent.com/16447251/42515234-de7ea0f6-848d-11e8-96fe-c44084a72af9.png)

这个滚动条经常看不到在哪。。。手不稳的时候还点不到！
改成黑一点，粗一点体验会好很多哦！谢谢:laughing:

**Comment by elmorec** [comment]
手抖吗，注意身体呀

**Comment by xujiaji** [comment]
一言难尽啊

**Comment by xujiaji** [comment]
@elmorec  作者大大，请问有考虑后期添加国内能访问的评论系统吗？

**Comment by elmorec** [comment]
有推荐吗，现在在考虑支持 github issue 实现的评论。

**Comment by xujiaji** [comment]
只知道多说，但早不能用了。你说的github搭建这个就不错了哈！😁
