### ISSUE TITLE
首页加载不出文章

### ISSUE THREAD

**Issue by Jooecy** [elmorec/hexo-theme-inside#26]
hexo g时提示：
(node:7852) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by elmorec** [comment]
这不是主题报的吧，请确认版本
- node ≥ 8
- hexo > 8

**Comment by Jooecy** [comment]
首页没有文章，只有一个undefined

**Comment by elmorec** [comment]
Node 的一个 api 在 10 以上的版本废弃了，已经改好了，你再试下，多谢支持。

**Comment by Jooecy** [comment]
没关系的，我以为是windows的原因，我重做了系统，做成了linux，用的node8。在8下不会有问题吧？

**Comment by elmorec** [comment]
Node 8 不会的。

**Comment by Jooecy** [comment]
谢谢了。非常喜欢，虽然用这个主题代价有点大。但是值得。目前问题已经解决。

**Comment by Jooecy** [comment]
Favicon图标怎么添加？

**Comment by elmorec** [comment]
丢到 source 目录就好了，这里还没有做成可配置。
源码如下
```html
<link rel="icon" type="image/x-icon" href="/favicon.ico">
```

**Comment by Jooecy** [comment]
丢到主题的sources目录还是hexo的source目录？

**Comment by elmorec** [comment]
主题

**Comment by xuxusheng** [comment]
也可以放在 hexo 的 source 目录下，然后在主题 _config.yml 文件里的 manifest 里设置对应的路径就好了
