### ISSUE TITLE
侧边导航样式

### ISSUE THREAD

**Issue by xuxusheng** [elmorec/hexo-theme-inside#28]
## 现状：

目前大屏时侧边导航是白色主题，小屏时侧边导航是黑色主题。

## 期望：

感觉小屏时的黑色主题更好看一点，希望大屏时也能是黑色主题，是否考虑下提供侧边导航主题的配置项？3Q~

![image](https://user-images.githubusercontent.com/15248446/43433622-bfc59e76-94aa-11e8-8513-31e43e83c974.png)

**Comment by elmorec** [comment]
我想一下，本打算把背景图都做成可配置的。

**Comment by Jooecy** [comment]
我觉得现在这样子更好看。
