### ISSUE TITLE
主题很赞，遇到了一些小问题

### ISSUE THREAD

**Issue by Luoyayu** [elmorec/hexo-theme-inside#30]
这些问题主要因为自己不会js,css，还望作者大大解决
格式：需求/问题，尝试/描述
- description post摘要无法显示，试了插件hexo-description未生效
- 自定义文章内容的宽度, 替换`main.js`中`max-width=900` 生效
- 定义一个在主页显示略缩图的量, 例如`pre-thumbnail`
- 原生Gist标签插件未生效 ，例如`{% gist 5bd5a2f0c126d8f60833973ca4b41749 find_cycle_in_graph.cpp %}` 
- ~~~超链接跳转在Chrome下会在`about:blank`这里停顿一下，Safari不会~~~
- 修改`index.ejs`使之支持mathjax公式 [修改后index.ejs](https://paste.ubuntu.com/p/vWGcFxD64t/) 遇到的问题：第一次载入网页无法渲染公式需手动刷新，例如从归档页跳转到post , 查了下是Angular无法动态加载第三方脚本
- 与hexo-blog-encrypt不兼容，无法检测到输入回车13
- 与Pandoc兼容不良，文章页目录按钮消失

**Comment by WincerChan** [comment]
与 hexo-blog-encrypt 不兼容的问题，可以把密码验证的函数挪到 `index.ejs` 的 `script` 标签，示例：[https://note.itswincer.com/posts/d67271d8](https://note.itswincer.com/posts/d67271d8)

**Comment by elmorec** [comment]
- 摘要不确定是不是主题导致，因为post内容的渲染基本都是按 hexo 默认的处理方式，我一般是使用`<!-- more -->`，见这里 https://hexo.io/docs/tag-plugins#Post-Excerpt。
- 内容宽度配置 appearance.content_width。
- pre-thumbnail 不知道想要什么特性，css 滤镜吗。
- gist 已支持 https://blog.oniuo.com/post/inside-theme-showcase#Gist。
- Chrome 下会在 `about:blank` 停顿的原因是，外链的 a 标签加了 `rel="noopener"`，考虑去掉了...没啥意思。

 其他问题你参考下主题最新的文档，看能否解决部分，如仍有兴趣，欢迎 再提 issue~
