### ISSUE TITLE
404页面是如何触发的？

### ISSUE THREAD

**Issue by Jooecy** [elmorec/hexo-theme-inside#31]
以你的Blog为例：[关于页面](https://blog.oniuo.com/about)Url为：[https://blog.oniuo.com/about](https://blog.oniuo.com/about)

如果此时我访问
`https://blog.oniuo.com/about11`
这是一个不存在的页面，并不会显示404页面，而是给出

`Not Found
The requested URL /about1 was not found on this server.`

而在coding page部署的博客则会显示coding page的404页面。

怎么样才能使用主题自带的404页面？

**Comment by elmorec** [comment]
因为整个网站实际上是个单页应用，路由都在前端，而路由有可能失败。

举个例子，如下配置：

```yml
menu:
  home: /
  about: /about
  test: /test
```

test 会出现在菜单栏，但这个 page 并不存在（比如你没敲过 `hexo new page test`），所以 `/test` 这个路由前端并不会定义，点它，就会跳到 `/404` 这个前端定义好的错误路由。

若直接访问这个地址，因为服务器上并不存在 `test/index.html` 这个文件，所以服务器显示 404。

若想统一：

1. 服务器设置 404 页面为主题生成的那个 404 页面；
2. 服务器设置所有请求都跳 `index.html`，把路由跳转交给前端。

两种都可以^_^。

**Comment by elmorec** [comment]
你再访问 [https://blog.oniuo.com/about11](https://blog.oniuo.com/about11) 试试
