### ISSUE TITLE
Not Picking Up Manifest File

### ISSUE THREAD

**Issue by emmanuelobo** [elmorec/hexo-theme-inside#33]
The theme is not picking up on the manifest.json file I created.

**Comment by elmorec** [comment]
The theme generate manifest.json itself using configuration here [_config.yml#L81](https://github.com/elmorec/hexo-theme-inside/blob/master/_config.yml#L81).

If you don't use this, just simply edit the template [layout/index.ejs#L9](https://github.com/elmorec/hexo-theme-inside/blob/master/layout/index.ejs#L9).

**Comment by emmanuelobo** [comment]
So I got it to generate. But it seems like its not even using the manifest file. It's using the properties from _config.yaml (base).


_Unrelated_ how do I add a link to my main site as one of the menu options? Everytime I try to add it to _config.yaml it's adding a '/' in front of the url automatically even without me adding it. So for example my setup will look like:

```
menu:
      home: /
      about: /
      site: http://espn.com

```

but I get a 404 error because it is giving the url as http://localhost:4000/http://espn.com

**Comment by emmanuelobo** [comment]
Nevermind! It worked this time around.
