### ISSUE TITLE
请问如何自定义文章的 URL

### ISSUE THREAD

**Issue by WincerChan** [elmorec/hexo-theme-inside#34]
比如我的想法是在每个文章的 front matter 添加一个自定义字段：
```markdown
---
title: Hello World
slug: d77abc78
---
```
使生成的文章是 `post/d77abc78` 而不是 `post/Hello-World`。
因为有些文章的题目是中文的，导致生成的 URL 也是中文的，有些不美观。
请问可以实现吗？

**Comment by elmorec** [comment]
slug 是 hexo 生成的，其实就是 md 的文件名，并不是 title 字段啊，举例：
```yaml
# _post/你好世界.md
---
title: 你好世界
---
```

最终的访问路径是 `/post/你好世界`。

但是，你可以改文件名啊。

```yaml
# _post/d77abc78.md
---
title: 你好世界
---
```

最终的访问路径是 `/post/d77abc78`。

是你要的效果吗。

**Comment by WincerChan** [comment]
原来是这样，谢谢告知
