### ISSUE TITLE
有的文章不显示目录

### ISSUE THREAD

**Issue by Jooecy** [elmorec/hexo-theme-inside#37]
![_ _20180814211352](https://user-images.githubusercontent.com/32447188/44093825-280e0c9a-a007-11e8-88e4-749b28079a5a.png)
最近新写的文章，都没有这个目录导航。检查了很多地方，没发现原因。请指教！

**Comment by elmorec** [comment]
目录是从 `# heading1` 开始尝试匹配，如果没有，就匹配 `## heading2`，也就是说你的 markdown 里，如果直接写了个三级标题或以下，是生成不了目录的，见源码 [lib/utils.js#L200](https://github.com/elmorec/hexo-theme-inside/blob/master/lib/utils.js#L200)。

建议正文的标题从二级标题开始，支持从一级标题开始只是为了兼容，之所以这样建议，是因为文章 title 是一级标题，正文如果需要标题，就往下一级从二级开始，这样很合理，不要跳级。
