### ISSUE TITLE
无法展示数据

### ISSUE THREAD

**Issue by xujiaji** [elmorec/hexo-theme-inside#4]
更新后打开页面不展示数据，在本地时候是正常的，但上传后就无法显示了。我不清楚这是什么原因造成的，你可以帮忙看看吗？谢谢！
地址：http://xujiaji.com

**Comment by elmorec** [comment]
这个打不开[http://xujiaji.com/api/_.json](http://xujiaji.com/api/_.json)...可能github有些什么限制吧，我换个文件名

**Comment by xujiaji** [comment]
嗯嗯，幸苦了

**Comment by elmorec** [comment]
@xujiaji 更新了

**Comment by xujiaji** [comment]
@elmorec 可以了└(^o^)┘
