### ISSUE TITLE
Tags页面无法显示标签

### ISSUE THREAD

**Issue by SakamotoMari** [elmorec/hexo-theme-inside#41]
左边栏可以显示tag的数量，但进入tags页面后显示为空白，不理解F12报的错与这有没有关系……请赐教（鞠躬
![tim 20180910221909](https://user-images.githubusercontent.com/19325616/45325073-d4a9bf80-b547-11e8-9da1-f661e0193a82.png)

**Comment by SakamotoMari** [comment]
> 有报错就有问题，可以看看你的配置吗
谢谢您的回复！
抱歉我对网站前端这些都不太熟悉，不知道您说的”配置“是指什么；
我在使用您的theme时，只修改了[_config.yml文件](https://github.com/SakamotoMari/sakamotomari.github.io/blob/hexo/themes/inside/_config.yml)，在source里添了几张图，没有作其他改动了。
tag页面的话在[这里](https://sakamotomari.github.io/tags)。
不知道是否需要提供计算机配置? win10， chrome 68.0.3440.106

**Comment by elmorec** [comment]
大概知道原因了，你是不是通过 `hexo new page tags` 建了个 page，`tags`、`categories`、`archives` 这些都不需要自己建页面的，你删掉试试。

**Comment by SakamotoMari** [comment]
> 大概知道原因了，你是不是通过 `hexo new page tags` 建了个 page，`tags`、`categories`、`archives` 这些都不需要自己建页面的，你删掉试试。

哇是的！删掉之后就正常显示了。
非常感谢！（鞠躬
以及谢谢你制作这款theme : )
