### ISSUE TITLE
Plugin load failed: hexo-theme-inside

### ISSUE THREAD

**Issue by Patrick-Jun** [elmorec/hexo-theme-inside#49]
我是从作者github上克隆的，然后复制在theme下，然后npm运行后，出现插件加载失败，目录无效，但是浏览器能正常打开博客，也没有发现错误。但就是存在那个错误，我有点纠结，然后我翻遍了那个文件，没有找到插件在那个目录，希望得到作者指点一下。
另外今天（2018.11.21）打开作者博客时，提示新浪云资源加载失败。
下面是命令行提示：
`
E:\我的文件\Blog>npm start

> hexo-site@0.0.0 start E:\我的文件\Blog
> hexo g && hexo s

ERROR Plugin load failed: hexo-theme-inside
Error: EISDIR: illegal operation on a directory, read
INFO  Start processing
INFO  Files loaded in 143 ms
INFO  0 files generated in 39 ms
ERROR Plugin load failed: hexo-theme-inside
Error: EISDIR: illegal operation on a directory, read
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
`

**Comment by elmorec** [comment]
hexo 的配置文件里有没有 plugins 相关的配置？

**Comment by elmorec** [comment]
😂欠费了，昨晚已经恢复了，谢谢你。

**Comment by Patrick-Jun** [comment]
找到原因了，是hexo的package.json里的dependencies多了“hexo-theme-inside”，也许它把这个认为是插件了。另外我修改了作者主题lib下的config.js文件
`const gravatar = require('../../../node_modules/hexo/lib/plugins/helper/gravatar');
const urlFor = require('../../../node_modules/hexo/lib/plugins/helper/url_for');`
因为我这个版本的hexo的gravatar和url_for文件并不在作者原来写的那个目录下，不改也没报错。
最后感谢作者提点。
