### ISSUE TITLE
发现一个自定义url生成问题

### ISSUE THREAD

**Issue by Patrick-Jun** [elmorec/hexo-theme-inside#50]
我需改hexo的_config.yml中的permalink，
将其改为：
`permalink: :category/:title.html`
然后重新生成，查看页面还是“https://域名/post/文章名”
我切换官方自带那个主题，就可以实现“目录/文章名.html”的效果
希望能得到您的指点。

**Comment by elmorec** [comment]
目前不支持自定义 url，因本质是单页应用，路由全部都由 js 重新定义，如果开放自定义路由，例如上面的路由，就已经和 page 路由冲突了。

**Comment by elmorec** [comment]
这个主题的 page 路由可以很灵活，支持嵌套。

**Comment by fightinggg** [comment]
> 目前不支持自定义 url，因本质是单页应用，路由全部都由 js 重新定义，如果开放自定义路由，例如上面的路由，就已经和 page 路由冲突了。

求作者大大支持这种写法 `permalink: :category/:title.html`
