### ISSUE TITLE
重新搭建了一下环境，不知道为什么表格显示不正常了

### ISSUE THREAD

**Issue by xujiaji** [elmorec/hexo-theme-inside#51]
一脸蒙蔽，只好来求救了！:grin:
在新电脑上，重新配置了下环境。`hexo s` 打开网页，表格就不正常了。是不是我缺了点啥？
> 原本是这样的：

![image](https://user-images.githubusercontent.com/16447251/49939960-40217580-ff19-11e8-9bca-d4ab0f23fae0.png)

> 现在显示如下：

![image](https://user-images.githubusercontent.com/16447251/49939638-5ed33c80-ff18-11e8-8391-d1b3a85767fd.png)

> 配置如下：

![image](https://user-images.githubusercontent.com/16447251/49940069-81198a00-ff19-11e8-8af8-9ea002d3b552.png)

**Comment by xujiaji** [comment]
不清楚怎么回事，重新`hexo init`初始化一个又正常了

**Comment by elmorec** [comment]
会不会是 `hexo s` 前没有执行 `hexo clean`。

**Comment by xujiaji** [comment]
额。。。确实没有
