### ISSUE TITLE
支持图片点击放大

### ISSUE THREAD

**Issue by zhoushuozh** [elmorec/hexo-theme-inside#57]
希望加入文章页图片点击放大功能。

**Comment by elmorec** [comment]
加上了 https://blog.oniuo.com/post/inside-theme-showcase#Image-click-to-zoom-in-out

**Comment by xujiaji** [comment]
@elmorec 更新了下主题，但是没有这个效果！

**Comment by elmorec** [comment]
markdown里有空行吗
```markdown
<!-- new line -->
![space](https://.../nh-pluto-moonlight.jpg)
<!-- new line -->
```

**Comment by xujiaji** [comment]
没有。。。

**Comment by elmorec** [comment]
[markdownlint](https://github.com/DavidAnson/markdownlint) 了解下，可以规范写作~

**Comment by xujiaji** [comment]
非常感谢:+1:
