### ISSUE TITLE
Disable comment section in posts

### ISSUE THREAD

**Issue by PoundKey** [elmorec/hexo-theme-inside#59]
你好，

如果帖子里面不想要 comments plugin 的话，2.0.1版本帖子底部会显示 `Load comments undefined`

能否在 config 里面添加一个 comments  = false 的选项，或者说，当 comments 被 comment 掉的时候 (e.g., # comments)， 主题就不会出现  `Load comments undefined`

谢谢！

**Comment by elmorec** [comment]
这个问题我发现了，配置没问题，支持 `false` 或者不写，或者注释掉，问题在：如果 post 没有 comments 这个属性，hexo 会默认给添加个 `comments: true`，暂时发现删除这个属性没用，但设置为 `false` 是可行的。

dev (https://github.com/elmorec/hexo-theme-inside/commit/5a1c886fb43cab70396615d3db1ad8fd51805025) 分支改好了，可以试下~

**Comment by PoundKey** [comment]
多谢🙏
会测试接下来的 release 并给出 feedback~
