### ISSUE TITLE
请教一下这个标签<is-d2a57d></is-d2a57d>是干嘛用的

### ISSUE THREAD

**Issue by i542873057** [elmorec/hexo-theme-inside#61]
在layout/index.ejs文件里有一个<is-d2a57d></is-d2a57d>标签，这个是干嘛用的。。我大致知道是内容渲染在这里的，但为什么是is-d2a57d，而不是is-8wersrw或者是其它

**Comment by elmorec** [comment]
is 是 inside 的缩写，`is-`  前缀的作用类似命名空间，原始的标签名大概叫 is-root、is-tag、is-v-post-list，这个 d2a57d 是 `md5('root')` 取前6位。

这样做至少有两个好处：

1. 混淆；
2. 可以节省一些字节，像 is-v-post-list 这样的名称很长。

我有一篇 blog 作了说明 [css-module-implementation-of-inside-theme#组建选择器](https://blog.oniuo.com/post/css-module-implementation-of-inside-theme#组建选择器)。
