### ISSUE TITLE
希望加个文章加密功能

### ISSUE THREAD

**Issue by Directoree** [elmorec/hexo-theme-inside#63]
因为这款主题不支持Hexo-blog-encrypt 这款插件！~~>_<~~

**Comment by elmorec** [comment]
试一下这个 https://github.com/elmorec/hexo-theme-inside/issues/30#issuecomment-412312708

**Comment by Directoree** [comment]
> 试一下这个 [#30 (comment)](https://github.com/elmorec/hexo-theme-inside/issues/30#issuecomment-412312708)

emmm...原答案的链接进不去了，加密函数实在是不好找😭

**Comment by elmorec** [comment]
[hexo-blog-encrypt/index.js#L94](https://github.com/MikeCoder/hexo-blog-encrypt/blob/801361b0ae3ebcbdd20835ce32270e0d448016de/index.js#L94), 94, 95, 96 三行代码删掉，在 layout.ejs 的 `<head>` 里添加：
```ejs
<%- js('lib/crypto-js') %>
<%- js('lib/blog-encrypt') %>
<%- css('css/blog-encrypt') %>
```

**Comment by elmorec** [comment]
## 补充

### 修改 hexo-blog-encrypt

1.[hexo-blog-encrypt/index.js#L94](https://github.com/MikeCoder/hexo-blog-encrypt/blob/801361b0ae3ebcbdd20835ce32270e0d448016de/index.js#L94), **line 94, 95, 96 删掉**，**新增一行代码**（与主题的目录解析有冲突，所以禁用目录），**修改一行代码**:
```diff
    data.content = data.template;
-   data.content += `<script src="${hexo.config.root}lib/crypto-js.js"></script>`;
-   data.content += `<script src="${hexo.config.root}lib/blog-encrypt.js"></script>`;
-   data.content += `<link href="${hexo.config.root}css/blog-encrypt.css" rel="stylesheet" type="text/css">`;

+   delete data.toc;
    data.more = data.abstract;
    data.excerpt = data.more;

  }
  return data;

-});
+}, 11);
```
2.[hexo-blog-encrypt/template.html#L1](https://github.com/MikeCoder/hexo-blog-encrypt/blob/801361b0ae3ebcbdd20835ce32270e0d448016de/template.html#L1), line1 删掉
```diff
- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
```

3.[hexo-blog-encrypt/lib/blog-encrypt.js#L113](https://github.com/MikeCoder/hexo-blog-encrypt/blob/801361b0ae3ebcbdd20835ce32270e0d448016de/lib/blog-encrypt.js#L114) line113 以下代码按如下修改：
```diff
// Since you decided to use jQuery.
-$(document).ready(
-  function () {
-
-    console.log('Registering Enter for decrypt.');
-    document.getElementById('pass').onkeypress = function (keyPressEvent) {
-
-      if (keyPressEvent.keyCode === 13) {
-
-        decryptAES();
-
-      }
-
-    };
-
-  }
-);
+$(document).on('keypress', '#pass', function (keyPressEvent) {
+  if (keyPressEvent.keyCode === 13)
+    decryptAES();
+})
```

### 修改主题 layout/index.ejs
```diff
+<%- js("https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js") %>
+<%- js("lib/crypto-js") %>
+<%- js("lib/blog-encrypt") %>
+<%- css("css/blog-encrypt") %>
</head>
```

### 最后

如果还不行，打开 chrome 控制台，看下是不是有个 callback 什么鬼的报错了，[hexo-blog-encrypt/lib/blog-encrypt.js#L33](https://github.com/MikeCoder/hexo-blog-encrypt/blob/801361b0ae3ebcbdd20835ce32270e0d448016de/lib/blog-encrypt.js#L33) 删掉下面那行......
```diff
      // Use jquery to load some js code
      try {

        $('#encrypt-blog').html(content);

-       {callback}

      } catch(e) {
```
