### ISSUE TITLE
配置data_prefix后，报了个错，无法显示文章列表

### ISSUE THREAD

**Issue by xujiaji** [elmorec/hexo-theme-inside#65]
如下

![image](https://user-images.githubusercontent.com/16447251/55711738-eb51bf80-5a1f-11e9-8cb3-2af73115073d.png)

**Comment by elmorec** [comment]
这是跨域了，和主题有啥关系~

**Comment by elmorec** [comment]
你看下阿里云的相关配置，白名单什么的~

**Comment by xujiaji** [comment]
噢噢😂原来如此，经常听说，没整过跨域的问题
