### ISSUE TITLE
想要 sidebar 上点击切换主题的功能！

### ISSUE THREAD

**Issue by omnibingo** [elmorec/hexo-theme-inside#67]
想要 sidebar 上点击切换主题的功能！可以开放出来让稍微有些修改代码能力的用户折腾一下吗，让我们一起做博客站里最靓的仔！

**Comment by elmorec** [comment]
不给🤡，那个效果没多复杂啊，或者你直接去我网站找，就几行 js，我只用了 5 分钟，加油~
