### ISSUE TITLE
添加搜索功能

### ISSUE THREAD

**Issue by awnawnawn** [elmorec/hexo-theme-inside#68]
主题如果再添加一个搜索功能就完美了

**Comment by elmorec** [comment]
有什么建议？

**Comment by BlackAwn** [comment]
hexo generator search 这个搜索插件不错。
我也尝试过配置，可能是主题文件有点难理解，没有配置成功

**Comment by elmorec** [comment]
那只是个 generator，我是指加到哪里、样式、如何交互等等~

**Comment by xujiaji** [comment]
如果加载右下角弹出菜单再添加个搜索按钮，点击搜索按钮出现个搜索弹框。不占地方，不影响其他风格样式，这样的交互你觉得咋样呢？

**Comment by BlackAwn** [comment]
> 那只是个发电机，我是指加到哪里，样式，如何交互等等〜

我的想法是这样的
![Snipaste_2019-04-22_10-30-53](https://user-images.githubusercontent.com/47672657/56480109-4341f900-64eb-11e9-9b96-79fd9e4cfd54.png)
![Snipaste_2019-04-22_10-41-24](https://user-images.githubusercontent.com/47672657/56480112-44732600-64eb-11e9-8157-7099800c8e30.png)

**Comment by elmorec** [comment]
可以是可以，就怕右下角那个按钮，一点开，发现有一坨按钮~

**Comment by elmorec** [comment]
不如这样吧，我加一个 /search 的路由，方便直接访问搜索，也方便配置在 sidebar，再加一个可以从右下角按钮打开的快捷弹层，但做成配置，各取所好吧~

**Comment by xujiaji** [comment]
> 不如这样吧，我加一个 /search 的路由，方便直接访问搜索，也方便配置在 sidebar，再加一个可以从右下角按钮打开的快捷弹层，但做成配置，各取所好吧~

给力

**Comment by BlackAwn** [comment]
我相信这是一个利大于弊的功能呢 ～～ @elmorec

**Comment by Directoree** [comment]
嗯，这个建议不错  等好久了！
