### ISSUE TITLE
BUG：categroies无法正常删除

### ISSUE THREAD

**Issue by zhangshen147** [elmorec/hexo-theme-inside#71]
首先说明：如果正常删除名称毫不相干的分类的话，是没有问题的，发现bug是因为我做了如下操作：
本来使用了一个名为`tech`的分类，后来有点强迫症，觉得首字母大写比较好，于是就把所有文章的类别都改为Tech了。然后发现即使重新执行`hexo clean`、`hexo g`、命令，也无法删除原来那个小写的`tech`分类了，猜想或许跟windows平台下大小写不敏感有关。
OS：Windows

![](http://ww1.sinaimg.cn/large/006aHI0Sly1g2enymzq8hj30ig03hq2q.jpg)

**Comment by elmorec** [comment]
应该和主题无关，看下 hexo clean 是否正常执行，或者手动删除 dist 和 db.json。

**Comment by zhangshen147** [comment]
> 应该和主题无关，看下 hexo clean 是否正常执行，或者手动删除 dist 和 db.json。

找到问题所在了，是因为_draft文件夹里的文章有这个分类，谢谢！
