### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by toperc** [elmorec/hexo-theme-inside#72]
1.  插入一个比较宽的视频，然后发现在小屏上右边出现越界了，视频右边紧靠屏幕边界，没有间隙。

2. 利用markdown编辑，采用键盘上的tab键代替```格式化一段文字，发现某行文字太长没有折行产生越界了，不能左右滑动。

**Comment by elmorec** [comment]
1. 怀疑是插入的视频设置了固定宽度，我加个最大宽度；
2. 对于使用 tab 键格式化的文本，我看看怎么兼容一下；
3. Thx!

**Comment by elmorec** [comment]
@elmorec 我看了代码，对 iframe 是有设置最大宽度的，请问你插入的视频是什么形式？

**Comment by elmorec** [comment]
@toperc  我看了代码，对 iframe 是有设置最大宽度的，请问你插入的视频是什么形式？

**Comment by toperc** [comment]
> 
> 
> @toperc 我看了代码，对 iframe 是有设置最大宽度的，请问你插入的视频是什么形式？

MP4的，默认宽度比较宽，放到手机上就出现这个问题了。markdown中最简单的一种插入方式:
`<video src="xxxx.mp4" controls="controls"></video>`

**Comment by Sokias** [comment]
@elmorec 在尝试插入bilibili视频的时候iframe特别小，甚至连b站的播放器的控件都弹不出来，也没法全屏……
![image](https://user-images.githubusercontent.com/9634147/57269525-5e4f6400-70ba-11e9-80a8-bbba0dcf544c.png)
这是代码：
`<iframe src="//player.bilibili.com/player.html?aid=35954036&cid=63382657&page=1" scrolling="yes" border="0" frameborder="no" framespacing="0" allowfullscreen="true"> </iframe>`

**Comment by elmorec** [comment]
@Sokias iframe 只限制了最大宽度 100%，其默认样式就是这样，只能自己设置宽高，比如 `style="width:600px;height:400px"`，或者使用 hexo 提供的 iframe tab，`{% iframe url [width] [height] %}`。
