### ISSUE TITLE
文章无法直接通过 URL 直达

### ISSUE THREAD

**Issue by omnibingo** [elmorec/hexo-theme-inside#73]
即便 URL 是向着 post/xxx 去的，但还总是先跳转到首页。貌似之前有类似问题 issue 过，我是来摇旗呐喊的...

**Comment by elmorec** [comment]
哪里的 url?

**Comment by omnibingo** [comment]
> 哪里的 url?

比如我的博客地址：talk2.it，有一篇文章：talk2.it/post/b，但我浏览器输入后者的地址，页面跳转后还是会最后到 talk2.it（首页）来。

**Comment by elmorec** [comment]
与主题无关，是你服务器强制大写转小写，导致页面 404。

你可以试试访问 `view-source:https://talk2.it/post/B/`，最终会重定向为小写。
