### ISSUE TITLE
添加插件

### ISSUE THREAD

**Issue by awnawnawn** [elmorec/hexo-theme-inside#74]
我想给主题添加aos的页面滚动效果，但是这似乎起不到效果，貌似文章是最是后渲染的。

有什么办法在文章渲染成功后 再加载我的js插件吗

![Snipaste_2019-05-07_20-53-22](https://user-images.githubusercontent.com/47672657/57301185-fa08c080-710a-11e9-9e01-3011961bf1a6.png)

**Comment by elmorec** [comment]
试试 [plugins](https://blog.oniuo.com/theme-inside/docs/misc#plugins)，会在渲染结束后执行脚本，但你的 js 可能要改，否则就频繁执行 `init()` 了。
