### ISSUE TITLE
插件gitment

### ISSUE THREAD

**Issue by awnawnawn** [elmorec/hexo-theme-inside#75]
我按照了配置步骤，百度许久，也没能解决gitment的问题。我的配置哪里出错了吗
![Snipaste_2019-05-11_18-06-17](https://user-images.githubusercontent.com/47672657/57568318-42c8be00-7418-11e9-9ed5-1d873730a402.png)
![Snipaste_2019-05-11_18-09-24](https://user-images.githubusercontent.com/47672657/57568322-44928180-7418-11e9-8b86-685e64d9392e.png)
![Snipaste_2019-05-11_18-06-50](https://user-images.githubusercontent.com/47672657/57568320-43f9eb00-7418-11e9-8040-8ed611017691.png)
![Snipaste_2019-05-11_18-08-31](https://user-images.githubusercontent.com/47672657/57568321-43f9eb00-7418-11e9-8ccc-932e026cd3df.png)

**Comment by elmorec** [comment]
都提示没初始化了，点登录去初始化啊，或者手动去 github 初始化

**Comment by awnawnawn** [comment]
> 都提示没有初始化了，点登录去初始化啊，或者手动去github初始化

![Snipaste_2019-05-11_19-01-00](https://user-images.githubusercontent.com/47672657/57568829-28dea980-741f-11e9-9730-e49b35e46e79.png)

点击了login，页面重新加载了一次，又变成了这个错误

**Comment by elmorec** [comment]
![image](https://user-images.githubusercontent.com/9206414/57568964-3f860000-7421-11e9-8eb8-393817d4da2f.png)

**Comment by awnawnawn** [comment]
我把 callback url 改回了 CNAME，重新 login ，授权后，重新加载文章页面，还是没有成功
![Snipaste_2019-05-11_19-01-00s](https://user-images.githubusercontent.com/47672657/57569182-d5bb2580-7423-11e9-95a3-a2702c38ad80.png)
![Snipaste_2019-05-11_19-31-4a6](https://user-images.githubusercontent.com/47672657/57569183-d653bc00-7423-11e9-86e0-2d2c86ef1bf0.png)
![Snipaste_2019-05-11_19-32-2s3](https://user-images.githubusercontent.com/47672657/57569184-d6ec5280-7423-11e9-8493-ae4e500b001d.png)

**Comment by elmorec** [comment]
你用 next 主题试一下看会不会
