### ISSUE TITLE
Firefox下右下角圆按钮显示错误

### ISSUE THREAD

**Issue by syaki07** [elmorec/hexo-theme-inside#77]
Firefox for mac 66.0.5下，右下角圆形按钮内的三个圆点不显示。

控制台报错：
* 解析 r 属性是遇到预期外的的值 .2rem。 main.dcb2507d5003b2c77884.en.js:1:183298
* 解析 cy 属性是遇到预期外的的值 -.8rem。 main.dcb2507d5003b2c77884.en.js:1:183298
* 解析 cy 属性是遇到预期外的的值 .8rem。 main.dcb2507d5003b2c77884.en.js:1:183298

Chrome，Safari均显示正常。

**Comment by elmorec** [comment]
忽略此问题...
