### ISSUE TITLE
侧边栏的 search

### ISSUE THREAD

**Issue by awnawnawn** [elmorec/hexo-theme-inside#78]
在配置 menu：下的 Search : /search，出现404。如何显示对应的搜索页面

**Comment by elmorec** [comment]
https://github.com/elmorec/hexo-theme-inside/blob/7c841df3d476b0338736c9dde00e25bf26c2ce56/_config.yml#L151

文档写的不够明白？

**Comment by awnawnawn** [comment]
可以了谢谢，原因是我new page “sreach” 了。

**Comment by elmorec** [comment]
这是从哪继承的习惯...
