### ISSUE TITLE
引入改主题之后category tag 目录怎么使用呀

### ISSUE THREAD

**Issue by lycpang** [elmorec/hexo-theme-inside#8]
引入改主题之后category tag 目录怎么使用呀，希望能指教一下

**Comment by elmorec** [comment]
遇到什么问题呢

**Comment by lycpang** [comment]
我一开始没有使用hexo new命令创建行的文件 导致没有目录选项 现在没有问题了。我今天才玩，看了好多文档写的都不是很详细
原始邮件
发件人:Elmore Chengnotifications@github.com
收件人:elmorec/hexo-theme-insidehexo-theme-inside@noreply.github.com
抄送:lycpang15311411916@163.com; Authorauthor@noreply.github.com
发送时间:2018年4月9日(周一) 19:25
主题:Re: [elmorec/hexo-theme-inside] 引入改主题之后category tag 目录怎么使用呀 (#8)


遇到什么问题呢
