### ISSUE TITLE
难以自定义

### ISSUE THREAD

**Issue by gitforziio** [elmorec/hexo-theme-inside#9]
作者你好，这款主题非常棒，我很想学习其中的代码细节。
但是代码是经过打包的，无法阅读，也难以加以修改了。
能否提供源码版本？谢谢。

**Comment by elmorec** [comment]
源码在这里 [https://bitbucket.org/elmorec/inside-front-end](https://bitbucket.org/elmorec/inside-front-end)

**Comment by gitforziio** [comment]
谢谢！
